### ISSUE TITLE
布局文件.xml 里的直接写的android:onClick() 如何做到埋点

### ISSUE THREAD

**Issue by focusyanng** [nailperry-zd/CodelessDA-Gradle-Plugin#14]
布局文件.xml 里的直接写的android:onClick() 如何做到埋点

**Comment by nailperry-zd** [comment]
@youngitboy click监听如果是在layout中使用android:onClick="xxxMethod"设置的暂时无法进行采集。这个设置监听的方法是利用Java的反射原理，去寻找对应的Method，而我们是通过拦截工程中的OnClickListener点击事件来进行监听的，因此无法实现监听。
