### ISSUE TITLE
className处理出错

### ISSUE THREAD

**Issue by iwantthink** [nailperry-zd/CodelessDA-Gradle-Plugin#15]
代码位置: InjectTransform-isJarNeedModify(File jarFile)

        className = entryName.replace("/", ".").replace(".class","")

出现问题: 仅后一个替换`.class`字符串的 函数生效.... className中的`/`符号并没有被替换掉

拆成俩条语句之后生效... 

         className = entryName.replace("/", ".")
         className = className.replace(".class", "")

**Comment by nailperry-zd** [comment]
@iwantthink 可能要考虑下Window与Mac下File.separator的差异
