### ISSUE TITLE
Return code 1 for dex process

### ISSUE THREAD

**Issue by liangxianshen** [nailperry-zd/CodelessDA-Gradle-Plugin#17]
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

我在您的代码里新增了如下代码：
sFragmentMethods.put('onAttach(Landroid/content/Context;)V', new MethodCell(
                'onAttach',
                '(Landroid/content/Context;)V',
                '',// parent省略， android/app/Fragment 或 android/support/v4/app/Fragment
                'Companion.onFragmentAttach',
                '(Ljava/lang/Object;)V',
                0, 1,
                [Opcodes.ALOAD]))
我知道是我哪里没有写对，但是通过借鉴您的代码和查阅ASM文档后发现不了问题，忘能得到指正

我自己发布了一个插件，这个插件只有在你的demo里是没问题的，但是我新建一个功能，配置和你的demo一模一样，仍然是报这个错

**Comment by nailperry-zd** [comment]
@liangxianshen Companion.onFragmentAttach配错了的样子。。

例如，
sFragmentMethods.put('onResume()V', new MethodCell(
                'onResume',
                '()V',
                '',// parent省略，均为 android/app/Fragment 或 android/support/v4/app/Fragment
                'onFragmentResume',
                '(Ljava/lang/Object;)V',
                0, 1,
                [Opcodes.ALOAD]))
待插入的方法名为onFragmentResume，所属类为sAgentClassName：
![image](https://user-images.githubusercontent.com/20455160/47993787-61798f80-e12b-11e8-9ba3-c6095abc1be1.png)

**Comment by liangxianshen** [comment]
我是用kotlin写的，所以必须要带上Companion.
问题是我下面这个方法都注入成功了:
sFragmentMethods.put('onDetach()V', new MethodCell(
                'onDetach',
                '()V',
                '',
                'Companion.onFragmentDetach',
                '(Ljava/lang/Object;)V',
                0, 1,
                [Opcodes.ALOAD]))
很郁闷

**Comment by liangxianshen** [comment]
我把所有的Fragment覆写上onAttach
@Override
    public void onAttach(Context context) {
        super.onAttach(context);
    }
奇迹般的好了，我继续去你的源码里找找答案去，如果大哥找到答案了也要及时通知小兄弟哈,
之所以在你demo里没问题，是因为我不知道什么时候将com.codeless.demo.fragment.BaseFragment覆写了onAttach

**Comment by nailperry-zd** [comment]
@liangxianshen 我之前设计的是，只对直接继承android/app/Fragment 或 android/support/v4/app/Fragment的Fragment进行注入

**Comment by liangxianshen** [comment]
> @liangxianshen 我之前设计的是，只对直接继承android/app/Fragment 或 android/support/v4/app/Fragment的Fragment进行注入

嗯嗯 是是 这没问题
但这不是问题的根源
我觉得问题出在visitEnd()的代码里 ，你可以向onAttach或者onActivityCreated里注入一下代码试试，只要desc括号里不是基本数据类型就会有问题
