### ISSUE TITLE
问个问题这个插件的正确引入方式是什么？

### ISSUE THREAD

**Issue by quelang9** [nailperry-zd/CodelessDA-Gradle-Plugin#3]
我通过Module方式引入，在build.gradle中按照文档中的方式引入会报错：
Error:(266, 0) Could not find method codelessdaConfig() for arguments [build_7d4m8ark868yosfs5856t9l9k$_run_closure7@21635d9d] on project ':app' of type org.gradle.api.Project.
<a href="openFile:/Users/user/Documents/develop/feel/Feel-android/app/build.gradle">Open File</a>

**Comment by nailperry-zd** [comment]
这个是插件，不能像library那样引入到应用中的。你需要打包插件到本地或远程仓库，然后apply plugin，这部分我暂时没有整理成文档。

**Comment by quelang9** [comment]
打包插件到本地是指使用gradle的build命令，将这个插件打成一个jar包吗？
这个插件的名字是com.codelessda对吧。
我刚才尝试通过引用jar包的方式去apply这个插件，还是报找不到这个插件？
如果我这个方式不对，能否告知一个正确打包插件到本地的方式，万分感谢！

**Comment by nailperry-zd** [comment]
稍等哈，一直没弄这个了，好多东西忘了，我去找找有没有什么文档

**Comment by quelang9** [comment]
好的谢谢，再问个问题。之前文档上提到的坑现在还有吗？

**Comment by nailperry-zd** [comment]
[Android字节码修改神器HiBeaver：黑掉你的SDK](https://segmentfault.com/a/1190000008491823)

**Comment by nailperry-zd** [comment]
这是原理

**Comment by nailperry-zd** [comment]
文档中提到的坑，关于ASM语法的部分解决了。至于v7兼容包的问题那应该是v7包冲突的问题了，与插件本身关系不大吧。

**Comment by nailperry-zd** [comment]
如何发布插件并引用插件，请参考[ 自定义gradle插件](http://blog.csdn.net/killer991684069/article/details/51776509)

**Comment by quelang9** [comment]
嗯嗯，这篇文章已经看过

**Comment by nailperry-zd** [comment]
当时为了剥除敏感信息，只把buildsrc的内容提交到git了

**Comment by nailperry-zd** [comment]
而且你应该需要修改ReWriterConfig这个配置类才能使用，在这个配置类中去定义要注入的方法相关信息

**Comment by quelang9** [comment]
嗯嗯，就是我自己的项目里需要创建PluginAgent这个类和对应的方法才行是吧？

**Comment by nailperry-zd** [comment]
是的呢，你的PluginAgent没有的方法就不需要在ReWriterConfig进行配置了，要是新增了方法，那也要对应地修改配置类

**Comment by nailperry-zd** [comment]
为了方便大家直接运行查看效果，我将整个project上传了，直接运行app module即可。大家可以参考app module示例直观了解插件是如何修改代码的，修改后的代码也可以直接从app/build下看到。文档也做了同步更新。

**Comment by hl372362624** [comment]
示例可以成功行动吗？ 我报了个错呀？
Gradle 'CodelessDA-Gradle-Plugin-master' project refresh failed 
Error:Connection refused

**Comment by nailperry-zd** [comment]
@hl372362624 能贴一下具体的错误吗？
