### ISSUE TITLE
大牛您好,一个关于使用的问题

### ISSUE THREAD

**Issue by lijinbolove** [nailperry-zd/CodelessDA-Gradle-Plugin#7]
`  
        OkHttpClient mOkHttpClient = new OkHttpClient();
        //创建一个Request
        final Request request = new Request.Builder()
                .url("https://github.com/hongyangAndroid")
                .build();
        //new call
        Call call2 = mOkHttpClient.newCall(request);
        //请求加入调度
        call2.enqueue(new Callback() {

            @Override
            public void onFailure(Call call, IOException e) {
                Log.e("@@@@", "失败");
            }

            @Override
            public void onResponse(okhttp3.Call call, okhttp3.Response response) throws IOException {

                Log.e("@@@@", "成功");
            }
        });
`

`
 sInterfaceMethods.put('onFailure(Lokhttp3/Call;Ljava/io/IOException)V', new MethodCell(
                'onFailure',
                '(Lokhttp3/Call;Ljava/io/IOException)V',
                'okhttp3/Callback',
                'onFailure',
                '(Lokhttp3/Call;Ljava/io/IOException)V',
                1, 2,
                [Opcodes.ALOAD, Opcodes.ALOAD]))
        sInterfaceMethods.put('onResponse(Lokhttp3/Call;Lokhttp3/Response)V', new MethodCell(
                'onResponse',
                '(Lokhttp3/Call;Lokhttp3/Response)V',
                'okhttp3/Callback',
                'onResponse',
                '(Lokhttp3/Call;Lokhttp3/Response)V',
                1, 2,
                [Opcodes.ALOAD, Opcodes.ALOAD]))
`

大牛您好,请问一下  我想在网络请求这块插入代码  这样写有什么问题吗,就在回调接口onFailure 和onResponse中调用

**Comment by nailperry-zd** [comment]
语法细节我也不是很清楚，推荐你使用一个字节码翻译工具Bytecode（Eclipse插件）
